import type { MentorRequest } from "./topicMentorContract";

export const sampleMentorRequests: MentorRequest[] = [
  {
    identity: {
      classId: "10",
      subjectKey: "maths",
      topicKey: "triangles",
      topicDisplayName: "Triangles",
    },
    mode: "BoardSteps",
    vibes: ["CBSE_BoardTeacher"],
    context: {
      anchorId: "triangles_bpt_similarity",
      anchorTitle: "Basic Proportionality Theorem",
      conceptTags: ["bpt", "similarity", "ratio"],
      expectedMarks: 4,
      difficulty: "Medium",
      boardExamStyle: true,
      studentMistakesToTarget: ["ratio inversion", "missing diagram labels"],
    },
    allowedAnchors: {
      keyDefinitions: ["similarity", "bpt"],
      boardPatterns: ["C", "D"],
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["bpt", "similarity"],
      preferredKinds: ["GeometryDiagram"],
      maxVisuals: 1,
      labelStyle: "cbse_clean",
    },
  },
  {
    identity: {
      classId: "10",
      subjectKey: "maths",
      topicKey: "trigonometry",
      topicDisplayName: "Trigonometry Graphs",
    },
    mode: "ConceptExplain",
    vibes: ["FriendlyCoach"],
    context: {
      anchorId: "trig_graphs_sin_cos",
      anchorTitle: "Sin and Cos graphs",
      conceptTags: ["trig", "graph", "period", "amplitude"],
      expectedMarks: 3,
      difficulty: "Medium",
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["graph", "trig"],
      preferredKinds: ["GraphPlot"],
      maxVisuals: 1,
      labelStyle: "minimal",
    },
  },
  {
    identity: {
      classId: "10",
      subjectKey: "maths",
      topicKey: "straight_lines",
      topicDisplayName: "Straight Lines",
    },
    mode: "ConceptExplain",
    vibes: ["StudentLens_Class10"],
    context: {
      anchorId: "straight_lines_slope",
      anchorTitle: "Slope and intercept",
      conceptTags: ["line", "slope", "graph"],
      expectedMarks: 2,
      difficulty: "Easy",
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["graph", "line"],
      preferredKinds: ["GraphPlot"],
      maxVisuals: 1,
      labelStyle: "cbse_clean",
    },
  },
  {
    identity: {
      classId: "10",
      subjectKey: "science",
      stream: "physics",
      topicKey: "light_reflection_refraction",
      topicDisplayName: "Light: Reflection and Refraction",
    },
    mode: "BoardSteps",
    vibes: ["CBSE_BoardTeacher"],
    context: {
      anchorId: "convex_lens_image",
      anchorTitle: "Convex lens image formation",
      conceptTags: ["ray", "lens", "image"],
      expectedMarks: 5,
      difficulty: "Medium",
      boardExamStyle: true,
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["ray", "lens"],
      preferredKinds: ["RayDiagram"],
      maxVisuals: 1,
      labelStyle: "cbse_clean",
    },
  },
  {
    identity: {
      classId: "10",
      subjectKey: "science",
      stream: "physics",
      topicKey: "electricity",
      topicDisplayName: "Electricity",
    },
    mode: "BoardSteps",
    vibes: ["CBSE_BoardTeacher"],
    context: {
      anchorId: "ohms_law_setup",
      anchorTitle: "Ohm's law circuit",
      conceptTags: ["circuit", "ohms_law", "ammeter", "voltmeter"],
      expectedMarks: 5,
      difficulty: "Medium",
      boardExamStyle: true,
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["circuit", "ammeter", "voltmeter"],
      preferredKinds: ["CircuitDiagram"],
      maxVisuals: 1,
      labelStyle: "cbse_clean",
    },
  },
  {
    identity: {
      classId: "10",
      subjectKey: "science",
      stream: "biology",
      topicKey: "life_processes",
      topicDisplayName: "Life Processes",
    },
    mode: "ConceptExplain",
    vibes: ["FriendlyCoach"],
    context: {
      anchorId: "neuron_structure",
      anchorTitle: "Neuron structure",
      conceptTags: ["neuron", "diagram", "nervous_system"],
      expectedMarks: 3,
      difficulty: "Easy",
    },
    visualPolicy: {
      requireVisuals: true,
      requireWhenConceptTags: ["diagram", "neuron"],
      preferredKinds: ["BioDiagram"],
      maxVisuals: 1,
      labelStyle: "minimal",
    },
  },
];
